inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 35  # Increased for plugin system complexity
  Exclude:
    
    
    
    
    
    - 'lib/numana/statistics/non_parametric_stats.rb'
    - 'lib/numana/statistics/one_way_anova.rb'
    - 'lib/numana/statistics/two_way_anova.rb'
    - 'lib/numana/plugin_configuration.rb'
    - 'lib/numana/plugin_configuration/**/*'
    - 'plugins/**/*'

Metrics/CyclomaticComplexity:
  Max: 10  # Increased for plugin system complexity
  Exclude:
    
    
    
    
    
    - 'lib/numana/statistics/non_parametric_stats.rb'
    - 'lib/numana/statistics/one_way_anova.rb'
    - 'lib/numana/statistics/two_way_anova.rb'
    - 'lib/numana/plugin_configuration/**/*'
    - 'lib/numana/dependency_resolver.rb'
    - 'lib/numana/plugin_conflict_resolver.rb'
    - 'lib/numana/plugin_validator.rb'
    - 'plugins/**/*'

Metrics/PerceivedComplexity:
  Max: 12  # Increased for plugin system complexity
  Exclude:
    
    
    
    
    
    - 'lib/numana/statistics/non_parametric_stats.rb'
    - 'lib/numana/statistics/one_way_anova.rb'
    - 'lib/numana/statistics/two_way_anova.rb'
    - 'lib/numana/plugin_configuration/**/*'
    - 'lib/numana/dependency_resolver.rb'
    - 'lib/numana/plugin_conflict_resolver.rb'
    - 'lib/numana/plugin_validator.rb'
    - 'plugins/**/*'

Metrics/ClassLength:
  Max: 150  # Increased for plugin system complexity
  Exclude:
    - 'lib/numana/file_reader.rb'
    - 'lib/numana/cli/commands/plugins_command.rb'
    - 'lib/numana/statistics_presenter.rb'
    - 'lib/numana/presenters/two_way_anova_presenter.rb'
    - 'lib/numana/dependency_resolver.rb'
    - 'lib/numana/plugin_configuration.rb'
    - 'lib/numana/plugin_configuration/**/*'
    - 'lib/numana/plugin_conflict_resolver.rb'
    - 'lib/numana/plugin_sandbox/capability_manager.rb'
    - 'lib/numana/plugin_sandbox/method_interceptor.rb'
    - 'lib/numana/plugin_loader.rb'
    - 'lib/numana/plugin_template.rb'
    - 'lib/numana/plugin_validator.rb'
    - 'lib/numana/plugin_error_handler.rb'
    - 'plugins/**/*'
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    
    
    
    
    
    - 'lib/numana/statistics/non_parametric_stats.rb'
    - 'lib/numana/statistics/one_way_anova.rb'
    - 'lib/numana/statistics/two_way_anova.rb'
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25  # Increased for plugin system complexity
  Exclude:
    - 'lib/numana/statistics_presenter.rb'
    - 'lib/numana/presenters/two_way_anova_presenter.rb'
    
    
    
    
    
    - 'lib/numana/statistics/non_parametric_stats.rb'
    - 'lib/numana/statistics/one_way_anova.rb'
    - 'lib/numana/statistics/two_way_anova.rb'
    - 'lib/numana/plugin_configuration/**/*'
    - 'lib/numana/dependency_resolver.rb'
    - 'lib/numana/plugin_conflict_resolver.rb'
    - 'lib/numana/plugin_error_handler.rb'
    - 'lib/numana/plugin_validator.rb'
    - 'plugins/**/*'
    - 'spec/numana/statistics/**/*'

Layout/LineLength:
  Max: 150
  Exclude:
    - 'numana.gemspec'
    - 'spec/**/*'

Style/EndlessMethod:
  EnforcedStyle: allow_single_line

Metrics/ParameterLists:
  Max: 7
  Exclude:
    - 'plugins/**/*'

Naming/MethodParameterName:
  Exclude:
    
    
    
    
    
    - 'lib/numana/statistics/non_parametric_stats.rb'
    - 'lib/numana/statistics/one_way_anova.rb'
    - 'lib/numana/statistics/two_way_anova.rb'
    - 'spec/numana/statistics/**/*'
    - 'plugins/**/*'

Naming/PredicateMethod:
  Exclude:
    - 'lib/numana/plugin_configuration/**/*'
    - 'lib/numana/plugin_sandbox/capability_manager.rb'
    - 'lib/numana/plugin_loader.rb'
    - 'lib/numana/plugin_template.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Lint/EmptyClass:
  Exclude:
    - 'lib/numana/plugin_system.rb'