inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Exclude:
    - 'lib/number_analyzer/file_reader.rb'  # Multi-format file reader (CSV/JSON/TXT) requires comprehensive methods

Metrics/AbcSize:
  Exclude:
    - 'lib/number_analyzer.rb'  # Statistical calculation methods have inherent complexity
    - 'lib/number_analyzer/statistics_presenter.rb'  # Display methods need to format 11+ statistical values

Layout/LineLength:
  Exclude:
    - 'number_analyzer.gemspec'  # Gemspec descriptions often exceed line length limits
    - 'spec/**/*'               # Test files often have long expectation strings
