inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'lib/number_analyzer.rb'  # Chi-square and other statistical methods require comprehensive calculations
    - 'lib/number_analyzer/cli.rb'  # CLI methods for chi-square parsing and subcommand handling
    - 'lib/number_analyzer/output_formatter.rb'  # Output formatting methods

Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - 'lib/number_analyzer.rb'  # Chi-square statistical methods have inherent mathematical complexity
    - 'lib/number_analyzer/cli.rb'  # CLI argument parsing and chi-square special handling

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - 'lib/number_analyzer.rb'  # Chi-square and statistical calculation methods require complex logic
    - 'lib/number_analyzer/cli.rb'  # CLI methods for chi-square parsing and option handling

Metrics/ClassLength:
  Exclude:
    - 'lib/number_analyzer.rb'              # Core statistical analysis with 16 statistical functions
    - 'lib/number_analyzer/file_reader.rb'  # Multi-format file reader (CSV/JSON/TXT) requires comprehensive methods
    - 'lib/number_analyzer/cli.rb'          # CLI class requires all subcommand implementations
    - 'lib/number_analyzer/output_formatter.rb'  # Output formatting for all statistical functions and CLI options

Metrics/AbcSize:
  Exclude:
    - 'lib/number_analyzer.rb'  # Statistical calculation methods have inherent complexity
    - 'lib/number_analyzer/statistics_presenter.rb'  # Display methods need to format 11+ statistical values
    - 'lib/number_analyzer/cli.rb'  # CLI argument parsing has inherent complexity
    - 'lib/number_analyzer/output_formatter.rb'  # Complex output formatting for chi-square and other statistical tests

Layout/LineLength:
  Exclude:
    - 'number_analyzer.gemspec'  # Gemspec descriptions often exceed line length limits
    - 'spec/**/*'               # Test files often have long expectation strings

Style/EndlessMethod:
  EnforcedStyle: allow_single_line
