remote_theme: mmistakes/minimal-mistakes@4.26.2
title: "til"
description: "Noriyo Akita's Today I Learned"
url: "https://noriyotcp.github.io/til/"
markdown: GFM
paginate: 5
paginate_path: /page:num/

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - projects

author:
  name: "Noriyo Akita"
  location: "Japan"
  email: "noriyo.akita@gmail.com"
  github: "noriyotcp"

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have onetheme: jekyll-theme-slate

