remote_theme: pages-themes/hacker@v0.2.0
title: "til"
description: "Noriyo Akita's Today I Learned"
url: "https://noriyotcp.github.io/til/"
markdown: GFM

author:
  name: "Noriyo Akita"
  location: "Japan"
  email: "noriyo.akita@gmail.com"
  github: "noriyotcp"

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have onetheme: jekyll-theme-slate

