import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '@/context/AuthContext';
import { GoalsProvider } from '@/context/GoalsContext';
import { WorkoutsProvider } from '@/context/WorkoutsContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WorkoutsProvider>
          <AuthProvider>
            <GoalsProvider>
              {children}
            </GoalsProvider>
          </AuthProvider>
        </WorkoutsProvider>
      </body>
    </html>
  );
}

export default RootLayout;
